version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 600941914653
    AWS_REGION: ap-south-1
    ECR_REPOSITORY: 600941914653.dkr.ecr.ap-south-1.amazonaws.com/adama_internal
    CLUSTER_NAME: prod-adama-Adama-internal
    DEPLOYMENT_FILE: deployment.yaml  # Using deployment.yaml as per your request

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Building Docker image...
      - docker build --no-cache -t adama_internal -f login-app/Dockerfile login-app/
      - docker tag adama_internal:latest 600941914653.dkr.ecr.ap-south-1.amazonaws.com/adama_internal:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 600941914653.dkr.ecr.ap-south-1.amazonaws.com/adama_internal:latest

      - echo Updating deployment.yaml with new container image...
      - sed -i 's@CONTAINER_IMAGE@'"$ECR_REPOSITORY:$IMAGE_TAG"'@' $DEPLOYMENT_FILE

      - echo Configuring kubectl for EKS...
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION

      - echo Deploying application to EKS...
      - kubectl apply -f $DEPLOYMENT_FILE
      - kubectl apply -f service.yaml
      - kubectl apply -f ingress.yaml

artifacts:
  files:
    - deployment.yaml
    - service.yaml
    - ingress.yaml
