version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPO: "adama_internal"
    IMAGE_TAG: "latest"
    AWS_ACCOUNT_ID: "600941914653"
    CLUSTER_NAME: "prod-adama-Adama-internal"

  secrets-manager:
    GITHUB_TOKEN: "github-token-id"  # AWS Secrets Manager for GitHub Token

phases:
  pre_build:
    commands:
      - echo "Retrieving GitHub token from AWS Secrets Manager..."
      - export GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id github-token-id --query SecretString --output text)
      - echo "Checking out the code..."
      - git clone https://bhargavsiripurapu:$GITHUB_TOKEN@github.com/bhargavsiripurapu/adama_deployment.git
      - cd adama_deployment
      - echo "Logging in to Amazon ECR..."
      - |
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo "Building the Docker image..."
      - |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG \
        -f login-app/Dockerfile .
      - echo "Pushing the Docker image to ECR..."
      - |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating Kubernetes deployment file with new image..."
      - |
        sed -i "s|image:.*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$IMAGE_TAG|" deployment.yaml
      - echo "Updating kubeconfig for EKS cluster..."
      - |
        aws eks --region $AWS_REGION update-kubeconfig --name $CLUSTER_NAME
      - echo "Applying Kubernetes manifests..."
      - |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f ingress.yaml
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - deployment.yaml
    - service.yaml
    - ingress.yaml

    
