version: 0.2

env:
  variables:
    AWS_REGION: "ap-south-1"
    ECR_REPOSITORY: "600941914653.dkr.ecr.ap-south-1.amazonaws.com/adama_internal"
    CLUSTER_NAME: "your-eks-cluster-name"
    DEPLOYMENT_NAME: "adama-app"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)  # Shortened commit hash

  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REPOSITORY:$IMAGE_TAG

  post_build:
    commands:
      - echo "Updating deployment file with new image..."
      - sed -i "s|image: $ECR_REPOSITORY:.*|image: $ECR_REPOSITORY:$IMAGE_TAG|g" deployment.yaml
      - echo "Applying deployment to EKS..."
      - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl apply -f ingress.yaml
      - echo "Deployment completed successfully!"

artifacts:
  files:
    - deployment.yaml
    - service.yaml
    - ingress.yaml
